# group_vars/web.yml
app_name: myflaskapp
app_user: flask
app_group: flask

app_dir: "/opt/{{ app_name }}"
venv_dir: "{{ app_dir }}/venv"

listen_port: 8000
server_name: "_"
# Ex: si vous avez un domaine : "example.com", sinon "_" pour default_server

python_pkg: python3
pip_pkg: python3-pip
venv_pkg: python3-venv

# Dépendances système utiles (ajustez au besoin)
os_packages:
  - git
  - curl
  - unzip
  - build-essential

# Gunicorn
workers: 2
threads: 2
worker_class: sync

# Nginx
nginx_client_max_body_size: 10m
